name: Smoke Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: dhall-lang/setup-dhall@v4
      - run: dhall text --file examples/single-job.dhall
      - run: dhall text --file examples/multiple-jobs.dhall
      - run: dhall text --file examples/inehrit-examples.dhall
